### ISSUE TITLE
Final tweaks before v1

### ISSUE THREAD

**Issue by pfraze** [ssbc/phoenix#231]
- [ ] update help entries
 - [x] get invite codes working again
 - [x] put "other given nicknames" back into the profiles
 - [x] standardize message formats (combine pub and profile, make gives-nick a special case of profile)
 - [x] make the network page usable
 - [x] put form to use invite code on the splash page
 - [x] finish pulling out any modules
 - [ ] QA pass

anything else?

**Comment by pfraze** [comment]
here is the current onboarding flow
![screen shot 2015-01-02 at 3 25 37 pm](https://cloud.githubusercontent.com/assets/1270099/5599809/c31a23f2-9293-11e4-83b7-2b191f6c69b9.png)
![screen shot 2015-01-02 at 3 25 56 pm](https://cloud.githubusercontent.com/assets/1270099/5599808/c317369c-9293-11e4-96b7-df240e4b86eb.png)
![screen shot 2015-01-02 at 3 26 06 pm](https://cloud.githubusercontent.com/assets/1270099/5599810/c31acb68-9293-11e4-889e-9806de4b23f2.png)

**Comment by jrf0110** [comment]
Since y'all are UI lazy, may I suggest at least getting a custom alert thingy going? http://tristanedwards.me/sweetalert

**Comment by pfraze** [comment]
@jrf0110 good idea thanks

**Comment by jrf0110** [comment]
Before V1, I reaaaaaaaaalllllly suggest ditching the bootstrap look and feel. It's a big turn-off (for me at least) when I see yet another bootstrap site

**Comment by kumavis** [comment]
edna_pirranah.css

**Comment by dominictarr** [comment]
+1 remove bootstrap

**Comment by jrf0110** [comment]
I don't know if removing bootstrap is the way to go (just depends on how much time you want to spend cascadin' in sheets, if ya' know what I mean) - But it is vey important that you divorce yourself from bootstrap default.

If you want to keep BS, I suggest:

1. Remove bootstrap from source and install from package management
2. Create your own Bootstrap Variables and Core files that are checked into source

This allows you to easily customize BS and to easily get updates when the time is right

**Comment by pfraze** [comment]
i agree, phoenix needs a distinct visual style. this was discussed in #82. we need to finish prototyping the ux first, but we're much closer to doing this now that users can post pictures

**Comment by ralphtheninja** [comment]
I have a designer friend that might want to sink his teeth into this. Want me to ask him to produce a couple of themes/styles? I meant pure visual design since he is not a front end dev.

**Comment by dominictarr** [comment]
@ralphtheninja +1 can they do css?

**Comment by ralphtheninja** [comment]
@dominictarr Unfortunately nope. But my thinking someone else could translate the visual design to suitable css.

**Comment by dominictarr** [comment]
hmm, maybe that is possible if it's clean and simple

**Comment by ralphtheninja** [comment]
Just spoke with him and he would love to create a couple of different designs. It will definitely be clean and simple. He likes to do "flat" designs. But first I need to set this up so I can show him how it works and the basic ideas.

**Comment by pfraze** [comment]
@ralphtheninja that'd be great. i have no problem converting images into the working web ui. can he get onto irc or a google hangout to discuss?

**Comment by ralphtheninja** [comment]
@pfraze He just left work but I can arrange for that tomorrow or another day.

**Comment by pfraze** [comment]
@ralphtheninja ok, i'll be available (I'm on CST hours)
