### ISSUE TITLE
address book ux

### ISSUE THREAD

**Issue by pfraze** [ssbc/phoenix#239]
how's this looking?

![screen shot 2015-01-05 at 11 57 37 am](https://cloud.githubusercontent.com/assets/1270099/5617245/3723bd22-94d2-11e4-843e-403eba104f54.png)

i got into one of those ux situations where a "trust" button felt better than a "use their address book" btn. it definitely means something different, but how do you feel about it?

in the "akas", the multiplier shows how many people use that name

**Comment by pfraze** [comment]
ignore the "anon," that wont stay

**Comment by pfraze** [comment]
styles tweaked

![screen shot 2015-01-05 at 12 11 40 pm](https://cloud.githubusercontent.com/assets/1270099/5617402/0937b06a-94d4-11e4-9051-3c7f28042ebb.png)

**Comment by dominictarr** [comment]
this looks good, athough we can't just count the votes - that is pretty easily attackable.
a short list of trusted nodes that use that name would be good though.

**Comment by dominictarr** [comment]
I added pagerank to graphmitter last night, and the suggest-box async pr will allow us to query sbot for ranked suggestions.

**Comment by pfraze** [comment]
> we can't just count the votes - that is pretty easily attackable.

right, we'd only see the name votes by people the user has "trusted"

**Comment by pfraze** [comment]
i'm inclined to say we should use trust ranking to establish orders but not to make security decisions. for instance,

 - security decision: "should i use the names by peer X?" answer: "only if the user explicitly trust-buttoned peer X"
 - non-security decision: "which of the names given by trusted peers should we use?" answer: "the one with the most reputable votes behind it"

**Comment by pfraze** [comment]
the trust button may be a bad idea actually. somebody sitting down for the first time would have no idea what that implies, and there are nuances to it

i'll see if i can make "use address book" work. at least that has clearer scope

**Comment by dominictarr** [comment]
okay so either way we have a ranking system for names based on user's expression of trust.
you are suggesting we use a simple thing that only counts votes from nodes a fixed number of hops away (basically, a descrete function) and I am suggesting a slightly more complex thing that uses a continious function.

but either way, we both agree about a list and ranking - how exactly to rank is a (potentially) pluggable detail.

**Comment by pfraze** [comment]
(to preface, something i said in irc - a security decision is a decision that, if made poorly, could open an attack vector)

yeah, i suppose my broader point is that i'm unsure about trusting security decisions to consensus (to the network). i feel more comfortable if i always choose whose address books i use

**Comment by pfraze** [comment]
![screen shot 2015-01-05 at 5 39 12 pm](https://cloud.githubusercontent.com/assets/1270099/5621987/cedaa958-9501-11e4-924f-3fba9bb692a4.png)
