### ISSUE TITLE
show trusts and flags in the address book

### ISSUE THREAD

**Issue by pfraze** [ssbc/phoenix#251]
should be able to see who you've trusted and flagged in the address book. even better, should be able to see trusts & flags by ppl you trust

no buttons (trust/flag btns should only be on the profile page)

**Comment by pfraze** [comment]
you can now see who youve flagged/trusted. should we see trusts-of-trusts and flags-of-trusts too?

**Comment by dominictarr** [comment]
what is a `flag-of-trust`? is that when someone is flagged by someone you trust?
should `flag` just be treated as negative trust?

**Comment by pfraze** [comment]
> what is a flag-of-trust? is that when someone is flagged by someone you trust?

yeah, basically a ui noticed `flagged by dominic`

> should flag just be treated as negative trust?

that's up to the ranking alg yeah?

**Comment by dominictarr** [comment]
ah right, yeah we should probably discuss this in another issue.
