### ISSUE TITLE
add peers to address book

### ISSUE THREAD

**Issue by pfraze** [ssbc/phoenix#259]
need to see the pubs and local nodes that you're connecting to. ideally, the peers will show their authenticated identities (i dont think we have that in scuttlebot yet). perhaps we can also show some connectivity-health metrics?

**Comment by dominictarr** [comment]
when you connect the first thing that happens is both sides authenticate so you know what keys-owners you are talking to. Also, who you are currently connected to can be queried from the gossip plugin

**Comment by pfraze** [comment]
:+1:

**Comment by dominictarr** [comment]
if we moved this to the server we could index all messages as they came in and then the order would be better defined.

**Comment by dominictarr** [comment]
oops, that comment was ment for https://github.com/ssbc/phoenix-api/issues/2

**Comment by pfraze** [comment]
is done
