### ISSUE TITLE
non-posts with replies should render in the posts view

### ISSUE THREAD

**Issue by pfraze** [ssbc/phoenix#264]
this was happening before but got lost somewhere along the way

if a non-post message has post replies, it should show up in the posts feed. that gives devs a chance to talk about behind-the-scenes stuff

**Comment by dominictarr** [comment]
what if instead of just using replies, we could have "related messages" which where messages that linked to the current message?

**Comment by dominictarr** [comment]
sorry, that idea should be a separate issue.
