### ISSUE TITLE
Ads should hide overflow

### ISSUE THREAD

**Issue by kumavis** [ssbc/phoenix#275]
Though it does look kinda cool without
![image](https://cloud.githubusercontent.com/assets/1474978/5806080/56c4440a-9fca-11e4-8fe8-32d540ee556e.png)

**Comment by pfraze** [comment]
hahaha that's awesome

**Comment by dominictarr** [comment]
btw, love how it really captures the adness with the different color etc

**Comment by pfraze** [comment]
i'm not sure i dislike this. we should see how else this manifests

**Comment by kumavis** [comment]
challenge accepted

**Comment by pfraze** [comment]
ads were removed
