### ISSUE TITLE
sync button - manually select a peer for gossip

### ISSUE THREAD

**Issue by pfraze** [ssbc/phoenix#282]
while debugging, i'll sometimes have to reboot my pub server. this causes it to fail gossip connect-attempts repeatedly, putting it lower in the gossip pool's priority-queue

once i have the server back online, i'd like to force scuttlebot to replicate with my pub immediately. i propose adding a button next to disconnected peers (in the address book) which forces a new connection attempt

**Comment by dominictarr** [comment]
I was thinking this too, we just need to add some commands to the gossip plugin to remove or add or connect to peers, and then we can access them from phoenix

**Comment by pfraze** [comment]
also going to add "connected X ago"

**Comment by pfraze** [comment]
done!
