### ISSUE TITLE
show 'posting' status until post is fully finished

### ISSUE THREAD

**Issue by pfraze** [ssbc/phoenix#284]
when a post is submitted, sometimes there's a delay where it appears that nothing is happening. phoenix should basically enter a "hold everything" mode until the post has succeeded/failed

**Comment by dominictarr** [comment]
Okay so is this just the period before the cb is called?

**Comment by pfraze** [comment]
yeah. when i implemented this, i was getting some occasionally very-long post times, and so would navigate away or try posting twice. i havent experienced that since, but this safe guards us

**Comment by dominictarr** [comment]
got it.
