### ISSUE TITLE
the ssb alt web

### ISSUE THREAD

**Issue by pfraze** [ssbc/phoenix#292]
starting with https://github.com/ssbc/phoenix/issues/289#issuecomment-71383701, i've been thinking about ssb as a tool for web publishing, and i think it has a compelling story that we should consider: the ssb "alt web."

once youre on the network you can publish files with no hosting setup or server rental. compared even to wordpress.com or medium it's low friction (no signup) and more in your control. the sites can grow to more sophisticated apps, but even simple static-content publishing is usable

 - no hosting or signup before publishing
 - data-rich network, [easy to inline information](https://github.com/ssbc/phoenix/issues/273) to published sites (comments, links, search metadata)
 - everything is backend-free and cloneable/forkable
 - browsing privacy (outbound traffic is controlled)
 - global asset sharing due to content addressing (only 1 jquery x.y.z blob)
 - "stream to own" - media doesnt go away after your first access

so how would this work? if you haven't used scuttlebot latest, we already have file publishing, and phoenix renders files by extension (supports images, pdfs, markdown, and html). the html is loaded in an iframe, and is able to load other assets attached to the message by relative paths

```html
<img src="foo.png">
```

it can also load assets by their content hash

```html
<img src="/ext/<hash>">
```

the rendering is done on a separate page (you click a link to the attachment) but we can easily inline the content on the post page and let the comments render below or beside. we might want to let the publisher specify how the attachments render in the publishing message.

attachments can also be viewed outside the phoenix ui (`localhost:2000/ext/<hash>`).

things to consider:

 - how can we link between published pages? this is difficult if 1) we dont have a permanent url scheme and 2) pages are in iframes, and thus not able to trigger top-level navigation. the 2nd issue may compel us to browse the ssb web outside of the phoenix ui? but then we'll need a good way to get to attached info (eg comments)
 - how might pages' js access the network apis (eg feeds)? if allowed to run outside of iframes, we'll need to consider the security concerns. it may be necessary to host the ext pages on a separate port than the phoenix app so that we can enforce different domain policies
 - how to handle versioning? it might be interesting to treat each feed as a domain with its own namespace, eg `/feed/<my-id>/index.html` would load the most recent `index.html` i've published. in fact, the index.html could function as the feed's "home page," same as existing domains.
 - we'd need a toolset to view/browse content before it's been published. this will be particularly important once pages can access the network apis, since they'll need testing

**Comment by jtremback** [comment]
When you say network APIs you mean scuttlebutt feeds exclusively, right?

**Comment by pfraze** [comment]
@jtremback yes to the feeds, but scuttlebot has a few other APIs (invites) and will accumulate more (crypto, ephemeral messaging)

**Comment by pfraze** [comment]
> What security concerns are there exactly?

mediating access to the APIs. most security tools the browsers give us are origin-based, so we'll need clever ways to assign permissions to individual pages

**Comment by pfraze** [comment]
https://github.com/ssbc/phoenix/pull/297#issuecomment-72131411

**Comment by pfraze** [comment]
http://www.technologyreview.com/news/534501/bittorrent-tests-websites-hosted-in-the-crowd-not-the-cloud/
