### ISSUE TITLE
pagination vs "load more"

### ISSUE THREAD

**Issue by pfraze** [ssbc/phoenix#295]
currently we have a "load more" button at the bottom of feeds to go past the initial set (which is usually ~30). it needs to be improved so that navigating away, then going back restores that state completely

but, before i do that, do we want to continue this approach, or consider a "page"-based approach? if we use pages, we could number the pages (0 being the oldest history, n being most recent) and then a user could bookmark a particular region of the history. this would also alter the UX a bit (left/right page arrows instead of a load more btn)

thoughts/preferences?

**Comment by dominictarr** [comment]
I think pagination is a much cleaner abstraction, and that linkability is a considerable win here.

**Comment by keybits** [comment]
+1 for pagination.

**Comment by pfraze** [comment]
https://github.com/ssbc/phoenix/pull/309

**Comment by pfraze** [comment]
implemented
