### ISSUE TITLE
paste.space auth failure

### ISSUE THREAD

**Issue by No9** [ssbc/phoenix#298]
So I have a fresh npm install scuttlebot@2.1.9

I have connected it with phoenix to my pub server at venshare.com 
That is fine and routing requests as expected. 

When I tried the URL to http://paste.space/ I get the initial screen with login enabled logout disabled 

Clicking login takes me to http://localhost:2000/auth.html?title=paste.space&perms=whoami&perms=add&perms=messagesByType&perms=createLogStream&popup=1&domain=http%3A%2F%2Fpaste.space 

When I click allow which just seems to be a link with a hash 

http://localhost:2000/auth.html?title=paste.space&perms=whoami&perms=add&perms=messagesByType&perms=createLogStream&popup=1&domain=http%3A%2F%2Fpaste.space# 

Nothing happens in chrome or firefox

**Comment by No9** [comment]
K the console output is 
```
 Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'self' data:". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.

http://localhost:2000/css/auth.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:2000/js/auth.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:2000/css/auth.css Failed to load resource: the server responded with a status of 404 (Not Found)
```

**Comment by pfraze** [comment]
aha. I bet this is an asset publishing on npm issue. one moment...

**Comment by pfraze** [comment]
it was - auth page's assets were not getting built and included in the package. updated as of `2.2.11`, give it a go

**Comment by No9** [comment]
Sorted thanks
