### ISSUE TITLE
random, enormous lags in message add

### ISSUE THREAD

**Issue by pfraze** [ssbc/phoenix#299]
i'm experiencing a sporadic delay in message publishing. it's completely inconsistent - sometimes `add` finishes quickly, and sometimes it's upwards of 15 seconds.

i haven't had a chance to try to isolate possible causes yet; just want to make sure we have an issue logged for it

**Comment by pfraze** [comment]
i tried to debug this during a flight and didnt experience it. there was no wifi, so gossip & replication wasnt occurring, which suggests the could be the culprits. possibly the sbot process getting locked up

**Comment by pfraze** [comment]
doesnt look like this is cpu throttling. i fired up node-inspector and took a cpu profile. here's the flame graph

![screen shot 2015-02-05 at 6 08 45 pm](https://cloud.githubusercontent.com/assets/1270099/6072031/2d967166-ad62-11e4-9bf9-1feb3ed8eafc.png)

that's the largest cpu usage (i believe that shows multiple aggregated calls) and its ~1ms. while collecting that profile, i did make a post that took multiple seconds

that leads me to think either leveldb is locked up, or there's a callback somewhere (maybe in the rpc stack) that's being held up

**Comment by dominictarr** [comment]
hmm, lets add logging for add times.
Okay here is an idea: maybe if this only happens when you are online, it's because of there are already many adds queued from replication? this seems unlikely though. we should add logging to scuttlebutt for time to call process add.

**Comment by pfraze** [comment]
https://github.com/ssbc/scuttlebot/pull/107 showed pretty clearly that the delay is occurring within ssb. I added some logging to the validation pipeline and that seems to be the culprit. I'm digging around for the specific issue now.

**Comment by pfraze** [comment]
https://github.com/ssbc/secure-scuttlebutt/pull/90
