### ISSUE TITLE
leave the nicknames used in @-mentions in the text

### ISSUE THREAD

**Issue by pfraze** [ssbc/phoenix#303]
presently, when somebody uses an `@-mention`, such as `@pfraze`, phoenix will go behind the scenes and replace the nickname with the full id -- something like `@kIetR4xx26Q2M62vG0tNrptJDFnxP0SexLHaOIkyy08=.blake2s`. this is so receiving peers can replace the id with the nickname they have for the user. for instance, if you've given me the name "pablo," then phoenix will replace that id with `@pablo`.

two problems with this:
 - if you dont have a nickname for that id, you're gonna see the base64 garbage
 - it's redundant information. each mentioned user is put in the message as a link, so the id (which is big) is in there at least twice

here's how a message looks now:

```js
{
  type: "post",
  text: "hey @kIetR4xx26Q2M62vG0tNrptJDFnxP0SexLHaOIkyy08=.blake2s",
  mentions: [{ rel: 'mention', feed: 'kIetR4xx26Q2M62vG0tNrptJDFnxP0SexLHaOIkyy08=.blake2s' }]
}
```

@dominictarr has suggested we put nicknames in the mention links:

```js
{
  type: "post",
  text: "hey @kIetR4xx26Q2M62vG0tNrptJDFnxP0SexLHaOIkyy08=.blake2s",
  mentions: [{ rel: 'mention', feed: 'kIetR4xx26Q2M62vG0tNrptJDFnxP0SexLHaOIkyy08=.blake2s', name: 'pfraze' }]
}
```

i propose we take it one step further and leave the text as-posted:

```js
{
  type: "post",
  text: "hey @pfraze",
  mentions: [{ rel: 'mention', feed: 'kIetR4xx26Q2M62vG0tNrptJDFnxP0SexLHaOIkyy08=.blake2s', name: 'pfraze' }]
}
```

this way...
 - a receiving peer can still sub out the locally-assigned nickname
 - a peer that doesnt know the mentioned user wont get base64 garbage in the message
 - the message doesnt have redundant ids

sho nuff

**Comment by kumavis** [comment]
having the peer stub out the name may be inappropriate if the nickname you gave it represents a personal relationship.

```
Attention @my_sweet_honey_pie, you have five days to return the borrowed items.
- borrow_bot
```

**Comment by pfraze** [comment]
that's crossed my mind. the thing is, we're already broadcasting these nicknames. that itself might be an issue.

**Comment by dominictarr** [comment]
I think this is pretty reasonable, though another option would be to use numbered references.
@kumavis has a good point, but lets put that in the 'too complex" pile for now.

**Comment by pfraze** [comment]
@dominictarr do you think the numbered references are worth it? it would shave off a few bytes, but it might be better to reduce the amount of processing needed

**Comment by dominictarr** [comment]
hmm, no it would be better to use names - and then the raw text would be more meaningful to the author.
