### ISSUE TITLE
make mentions clickable in message summary view

### ISSUE THREAD

**Issue by dominictarr** [ssbc/phoenix#305]
in a top-post that mentions users, since the whole post is rendered as a link, then the @user links are unclickable.
eg:
http://localhost:2000/#/msg/NBRiDGMOirSZHnwNLt5H2Ciy4J+6m4rxcTN8mj1ksAY=.blake2s

**Comment by dominictarr** [comment]
oh just realized i was looking at an old version here. it's not as bad in the new version, because on the message view it's rendered the same as the other replies.

**Comment by pfraze** [comment]
yeah. do we want at-mentions to be clickable within the message-list view?

**Comment by dominictarr** [comment]
i think so, and also in the author column... that is what you'd expect, i think.
