### ISSUE TITLE
Switch default port to 8008

### ISSUE THREAD

**Issue by No9** [ssbc/phoenix#306]
Is there any chance that we could default a higher port than 2000
My mobile carrier seems to block that for some reason. 
https://community.vodafone.ie/t5/Billpay-Packages/Possible-Blocked-Ports/td-p/44749 

Would something in the 8000 range be more normal?
http://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers

**Comment by dominictarr** [comment]
you can run your pub server on a different port by setting the port in the config,
you'll need to repost the pub message, then other peers will find it.

**Comment by dominictarr** [comment]
that is a message that look like this:

``` js
sbot.feed.add({
  type: 'pub', address: 'www.venshare.com:8000'
}, cb)
```

or, from the cli,

```
sbot add --type pub --address www.venshare.com:8000
```

**Comment by No9** [comment]
Thanks @dominictarr  
I can fix that alright but I was more thinking for general users/usage in the future.
If we want an install and go this type of thing can be annoying for users.

**Comment by dominictarr** [comment]
yes. I am not opposed to changing the default.

**Comment by No9** [comment]
OK Is it something I should PR and we can discuss with more folks?

**Comment by pfraze** [comment]
@No9 have you confirmed that those ports are blocked? that thread doesnt give any definitive info

i'm not opposed to changing it but we should do it before we have many more users

**Comment by No9** [comment]
Yes I have been fighting it today on my phone. 
Vodafone gave a service not available from their proxy so it was a pain chasing it down and not intuitive as it looked like my server was down as opposed to them blocking it. 

As per the wiki page it is more standard to run these alt_web services in the 8000 bracket but I understand we are not standard here :)

**Comment by pfraze** [comment]
the 8000 range tends to get used a lot in dev servers (and sometimes in production). what about port 9000?

**Comment by No9** [comment]
I hear you on using 9000 but the idea is that we use something from 8000 because it has more chance of being open on more networks. 
If a dev is running something on 8080 she is going get a EADDRINUSE and know what to do about it.
Where as we are potentially cutting off corporate users (I can't access from my work network either) and certain mobile network carriers. 

How does 8021 sound?

**Comment by dominictarr** [comment]
Down the road, we are probably gonna end up running on multiple ports (it's the simplest way to have upgradable crypto) so which default port we choose now is probably not a long term decision we need to carefully make.

Though, we might aswell use a port that is not officially assigned to something important, or use one that is assigned to something suitable...

http://www.tcp-udp-ports.com/port-8008.htm

So I suggest port 8008: _http-alternate_ sounds appropriate, no?

**Comment by No9** [comment]
:+1:  8008 LGTM 
I think any potential clash with "IBM HTTP Server administration" is the lesser of two evils.

**Comment by pfraze** [comment]
Ok, 8008 it is.

**Comment by pfraze** [comment]
Just had this come into play. The University of Rochester (NY) blocks outgoing requests for grimwire at 2000, but allows 8008.

**Comment by No9** [comment]
![Dancing](http://media1.giphy.com/media/12XTNObsY1pWQU/giphy.gif)

This has just made an old man happy 
Should we close this ticket BTW ?

**Comment by pfraze** [comment]
Let's keep it open till the PRs are closed and we're past any bugs.

**Comment by pfraze** [comment]
finally finished!
