### ISSUE TITLE
Raw feed UI feature additions

### ISSUE THREAD

**Issue by pfraze** [ssbc/phoenix#323]
Some missing features I've discovered while debugging

Need to be able to:

 - View messages (on the msg page) which are not posts
 - View blobs referenced by non-post messages
 - Filter the feed view with arbitrary js statements
 - Use pagination on feed view
 - View a profile page as a raw feed

**Comment by dominictarr** [comment]
... and view a single message as a raw message

**Comment by pfraze** [comment]
This is all done now except the profile page, which I'll handle today.

**Comment by pfraze** [comment]
ok, all set!
