### ISSUE TITLE
Moving from indexeddb to sbot's levedb storage via the phoenix api

### ISSUE THREAD

**Issue by pfraze** [ssbc/phoenix#333]
I began using level.js on indexeddb to store private user state such as "which messages have been read" and "which messages has the user subscribed to." I made that choice believing indexeddb was reliably persistent, but that turns out not to be the case. In https://lists.w3.org/Archives/Public/public-webapps/2013OctDec/0830.html they describe a "temporary storage" policy where a hard limit is enforced by ejecting the oldest writes. (Max Ogden, author of level.js, confirmed this.)

More related reading:
https://groups.google.com/a/chromium.org/forum/#!topic/chromium-html5/xtJ_uFeRs_U

And a bad sign that it's not going to be solved soon:
https://lists.w3.org/Archives/Public/public-webapps/2013OctDec/0980.html

The state I'm storing isn't critical, but it's not something users should ever have to lose. (Can you imagine if your inbox suddenly forgot which messages you've read? No sir!) 

I think the only logical solution is storage hosted by scuttlebot. We've talked in the past about adding a leveldb api to sbot for applications to use. I'm not yet sure if that's a good idea. We're still figuring out what kind of applications sbot will support, and a leveldb API opens up complex questions about permissions and resource usage quotas.

The alternative I'm going with (unless anybody objects strongly) is adding methods to `phoenix-api` for these features, eg `api.markRead(key, cb)`, `api.markUnread(key, cb)`, `api.isRead(key, cb)`, and so on. Internally, phoenix-api will store the data in sbot's leveldb instance. That way, we can get persistent storage, but don't go so far as to expose leveldb directly.

**Comment by dominictarr** [comment]
this seems reasonable, as long as the plugin keeps it's own data in a separate sublevel or separate level instance.

**Comment by ralphtheninja** [comment]
:+1: for not exposing the db but instead having a `DAL`

**Comment by pfraze** [comment]
This change has been made
