### ISSUE TITLE
Smoother message-stream scrolling

### ISSUE THREAD

**Issue by pfraze** [ssbc/phoenix#335]
The message-stream component is a gui for listing the feed vertically. It's used in the home page (and inbox and profile page) of the current phoenix (`3.0.3`).

It is an infinite scroller. The issues are

1. Scrolling will stutter sometimes due to loads.

2. There's a ui jank - the feed, when at `scrollTop==0`, must be scrolled down, then back up, to trigger the message-loader. This is because the browser does not emit a scroll event when the user tries to scroll past the top.

Instead of loading new messages when the user reaches the edge, the fetch should trigger within some range of the edge.

The app should also stream new messages to any active feeds (capped at the buffer size). This will solve the ui jank issue.

**Comment by dominictarr** [comment]
so when did you change your mind about infinite scroll?

**Comment by pfraze** [comment]
When I realized that this is a desktop app, not a web app.

**Comment by dominictarr** [comment]
hmm, why does that make it different? because you don't share links?

**Comment by pfraze** [comment]
No no, just that the performance characteristics are better. I'm finding I can make more round-trips to the database, even during the render process, without introducing lag. It's very convenient! It also means that controls like infinite scroll work very well.

I dont think we should ever lose linkability. The message-stream control can permalink at messages, but I havent added the button for it yet.

**Comment by dominictarr** [comment]
RIGHT. yes got it.

**Comment by pfraze** [comment]
Streaming new messages into active message-stream controls was, unsurprisingly, more complex than I wanted it to be. I ended up finding a nice hack (https://github.com/ssbc/phoenix/pull/339) which allows vertical scroll events to work at the top of the feed.
