### ISSUE TITLE
Migration script to update feeds to the new linking format and message types

### ISSUE THREAD

**Issue by pfraze** [ssbc/phoenix#341]
All existing feeds are going to need to republish a lot of information to update to the new version. I propose that we write a CLI tool to do this for people, to make that process more painless.

**Comment by dominictarr** [comment]
should we do this automatically, or just leave it?

**Comment by pfraze** [comment]
I think i can throw together a cli tool and publish it as a module, eg `sbot-migrate`, to do this kind of work

**Comment by dominictarr** [comment]
sounds good.

**Comment by pfraze** [comment]
Ship kinda sailed on this one, sorry guys
