### ISSUE TITLE
Internet points - proposal for adding up/down votes

### ISSUE THREAD

**Issue by pfraze** [ssbc/phoenix#350]
Freeform reactions got factored out of phoenix because, despite being fun, they didn't quite do the job I wanted them to do. Specifically I think reactions ought to do two things:

 1. Be simple
 2. Provide information-quality signals

RE: 1, I felt it was too tedious to create reactions (I'll write a reply if I want to do that) and I didn't love the UI (who looks at the list of reactions at the bottom of a tumblr and thinks, "yes, this is how it should work?" a condensed number of stars/upvotes/likes/retweets/etc is much more informative)

RE: 2, a generalized up/down vote system interests me for SSB, because it can be applied uniformly (all messages can be voted on) and interpreted diversely by applications (search, sorting/prioritization, archival). It's also useful socially.

Social networks which emphasize personal relationships tend not to allow downvotes. I think that's for weenies. The signal is richer if we allow negative values, and when you have to do real work (which phoenix is intended to do) it's actually better if teams can get aggregated views of their views.

So I suggest we have up and down votes, and that we represent them in phoenix as up/down votes (rather than stars, favorites, likes, etc).

I also suggest a message schema which is specific and can't be repurposed, to keep it simple:

```js
{
  type: 'vote',
  subject: { link }, // feed, msg, or ext
  vote: -1|0|1
}
```

Feel free to upvote/downvote this idea.

**Comment by pfraze** [comment]
here's a weird thing, you can upvote and downvote your upvotes and downvotes

**Comment by jrf0110** [comment]
yeah, but maybe UI's make a decision on what they want to show (that is, they don't want to show a chain of `n` upvotes on an upvote...)

**Comment by pfraze** [comment]
...right

**Comment by pfraze** [comment]
wasnt planning on doing otherwise

**Comment by dominictarr** [comment]
@pfraze maybe we have a "like" button and "passive-aggressive-like" button.

**Comment by jrf0110** [comment]
WELL! You never know!

**Comment by pfraze** [comment]
`like` and `"like"`

https://github.com/ssbc/phoenix/issues/351 is a working implementation of this, so really we just need to decide whether we do want up/down votes or stars or smiley stickers or whathaveyou

**Comment by dominictarr** [comment]
@pfraze I think that the upvoting the upvote is good actually. occasionally I've wanted to favorite a retweet or retweet a particularily witty favorite. language is weird. and maybe you'd want to delete an upvote? it's basically the same mechanism.

**Comment by pfraze** [comment]
@dominictarr agreed, just a matter of getting the ui right. right now Im hiding all the vote messages, though they can be seen in the "data" tab of the feed

**Comment by pfraze** [comment]
I suppose we could render the individual votes in the thread, maybe after all the other replies, maybe behind a toggle

**Comment by pfraze** [comment]
Up/down votes were added for messages, closing
