### ISSUE TITLE
inbox - can't tell which messages are new

### ISSUE THREAD

**Issue by kumavis** [ssbc/phoenix#363]
Ignore the red box... can't tell which message is the new message so i can clear my inbox

![image](https://cloud.githubusercontent.com/assets/1474978/6986751/46c2d49e-d9f5-11e4-88ec-d240723cc72d.png)

**Comment by kumavis** [comment]
X-POST http://localhost:2000/#/msg/Db7Blwi2VAWNgvhcySLswMt6FaRFGT5KztpnPWmB2gw=.blake2s

**Comment by pfraze** [comment]
There's a bug in that version which messes up the inbox ordering. It's fixed in https://github.com/ssbc/phoenix/pull/362

But we probably need some visual indicator of read/unread, eh?

**Comment by pfraze** [comment]
@kumavis phoenix `4.4.3` includes a fix, let me know if you still experience the issue.

**Comment by kumavis** [comment]
thanks!
