### ISSUE TITLE
Missing profile object causes error

### ISSUE THREAD

**Issue by clehner** [ssbc/phoenix#367]
When I visit the profile page for my [newly created pub server](http://localhost:8008/#/profile/Gj+u7XFTUbnA4ggEITowgBEtgWIlqdDcLD9h1r43Fvk=.blake2s), the page doesn't load and the web inspector shows errors because the profile object is null. I checked `sbot log` on the server and it is empty - not even a type: init message. Without any messages, getProfile in phoenix-api never gets called for the pid so the api never creates a profile object for it. I think there are two issues here.

1. What should the profile page show for a pid we don't know about? Should it try to validate the pid and show an empty profile if it is valid, and an error message if not?
2. Should sbot publish an init message when creating its keypair, and/or when it finds it has an empty feed, so that new pub servers get a profile? It looks like it is only making an init message now when it is triggered to make another message, following the behavior in [ssb-feed](https://github.com/ssbc/ssb-feed/blob/master/index.js#L64).

**Comment by pfraze** [comment]
Good catch. We can discuss 2 in the PR you made.

The right behavior for a not-found profile is...

 - Check if the id is good (`isHash` in https://github.com/ssbc/ssb-msgs).
  - If it isn't, explain the ID is invalid and dont show a profile page.
  - If it is, show an empty profile page and explain no messages have been found yet for the user. The profile controls (including follow btn) should be available.

**Comment by clehner** [comment]
Got it. Opening a PR now.
