### ISSUE TITLE
Trying to run latest version of Scuttlebot, Phoenix gives a CSP issue.

### ISSUE THREAD

**Issue by ootoovak** [ssbc/phoenix#372]
I think this is due to the changing of ports recently.

Steps:

Running `node bin.js server` in scutlebot fires up the server. http://localhost:2000 no longer works and gives an error  but http:localhost:8008 kind of works. There isn't an error but a grey background. Opening up the browser console (in Chrome) shows the following errors:

```
Resource interpreted as Script but transferred with MIME type text/plain: "http://localhost:8008/manifest.js".

Refused to connect to 'ws://localhost:2000/' because it violates the following Content Security Policy directive: "connect-src 'self' ws://localhost:8008".

Uncaught SecurityError: Failed to construct 'WebSocket': Refused to connect to 'ws://localhost:2000/' because it violates the document's Content Security Policy.
```

This looks to come from `home.js` so I think this is the right place to report it. :smile:

**Comment by ootoovak** [comment]
@pfraze @dominictarr I got  this working locally. I just had to reference the new `ssb-address` -> `ssb-channel` -> `phoenix`. So a fix from what I can tell is pushing a new version of `ssb-address`, then changing the *package.json*'s up the chain. :+1:

**Comment by pfraze** [comment]
Ah, yeah the build was compiled with the old default port. I'll update it to use `window.location`, so that reconfigs are tolerated.

**Comment by pfraze** [comment]
github autoclosed -- lmk if it's not solved for you
