### ISSUE TITLE
Moving to electron

### ISSUE THREAD

**Issue by pfraze** [ssbc/phoenix#395]
Phoenix works when loaded over http in an electron frame. Can we remove the http and load from the FS using electron? Is the electron IPC a secure channel (from other processes)? Will we be able to load untrusted content in the future (apps)?

Notes / resources:

 - [Safe ipc between browser and app](https://github.com/atom/electron/issues/456) - IPC isnt possible with node integration features off, so untrusted content will need another channel (websockets, comm with a parent frame, etc)
 - https://dev.chromium.org/developers/design-documents/inter-process-communication general info about IPC
 - https://github.com/atom/electron/blob/master/docs/api/browser-window.md#event-new-window We can intercept this to give custom behaviors on links with `target=_blank` - eg, load in the default browser
 - Loading phoenix from a file, CSP can be set with `<meta http-equiv="Content-Security-Policy">`. I'd bet the current version of chromium supports [CSP2's hash policies](http://www.w3.org/TR/CSP2/#source-list-valid-hashes).

Todo:

- [x] Remove sbot's HTTP endpoint, replace with TCP
- [x] Restructure Phoenix as an Electron app
- [x] Replace the websocket with Electron IPC
- [x] Create a protocol for blobs, switch the UI's URLs over
- [x] Open all target=_blank links in the user's browser
- [x] Fallback images on not found for `ext:`s
- [x] Notfound interface for `ext:`s opened but not found

**Comment by ralphtheninja** [comment]
+1 I'm in favor of this, just because I think it can improve adoption if it's packaged. More convenient that way and you can serve multiple platforms by e.g. using pre built binaries for leveldown etc.

**Comment by pfraze** [comment]
[Looks like serviceworkers are supported](https://github.com/atom/electron/issues/1331)

**Comment by pfraze** [comment]
[Debugging webviews with the remote proto](https://github.com/atom/electron/issues/1179)

**Comment by pfraze** [comment]
[We can register custom protocols](http://electron.atom.io/docs/v0.28.0/api/protocol/) which could be a good solution for hosting blobs, among other things.

**Comment by pfraze** [comment]
@dominictarr going to do a restructure:

- `electron-scuttlebot` will require `ssbplug-phoenix` (which I think we can rename to `ssb-phoenix` or somesuch). This will keep phoenix as a separate app in anticipation for when phoenix is delivered via ssb
- everything in `/src` and `/js` will be moved to the top-level and into `/lib` or `/vendor` directories, depending on their provenance
- the other directories will continue to live as-is
- scuttlebot will no longer import phoenix

We need to decide what to do with `phoenix-api`. For now, I suggest we import it directly into scuttlebot and keep it as-is. In the long-run, I think we should pull out anything we want to standardize (eg anything to do with profiles could go in the `friends` plugin or in a `users` or `profiles` plugin) and move anything else into the phoenix app (out of the scuttlebot process), as that will mimic the ssb-delivered apps.

**Comment by dominictarr** [comment]
sounds good!

**Comment by pfraze** [comment]
Ok, the checklist is done here. Closing
